/**
 * Workout reshaping for display.
 *
 * Reshape only: filter, group, sum, count, sort, format.
 *
 * Two wire constraints shape this file:
 *   1. `WorkoutSessionSummary` carries no `plan_id` / `session_plan_id` — that key exists
 *      only on events. Roadmap plans and execution history are therefore independent
 *      sources and are never joined row to row here.
 *   2. The roadmap uses `google.type.Date`, history uses `google.protobuf.Timestamp`, so
 *      both sides normalize to a day key first.
 */

import type { CalendarDateLike, DayKey, TimestampLike } from "./day-key";
import { dayKeyFromCalendarDate, dayKeyFromTimestamp, dayKeyRange, weekdayLabel } from "./day-key";

/** `SessionPlanStatus` as generated by protoc-gen-es. */
export const SESSION_PLAN_STATUS = {
  ABORTED: 4,
  COMPLETED: 2,
  PENDING: 1,
  SKIPPED: 3,
  UNSPECIFIED: 0,
} as const;

/** Structural subset of `SessionPlan`. */
export type SessionPlanRow = {
  scheduledDate?: CalendarDateLike;
  sessionPlanId: string;
  slotTime?: string;
  status: number;
  targetMuscleGroups?: string[];
};

/** Structural subset of `WorkoutSessionSummary`. */
export type SessionHistoryRow = {
  averageFormScore?: number;
  date?: TimestampLike;
  sessionId: string;
  totalSets: number;
  totalVolume: number;
};

export type Adherence = {
  completed: number;
  percentage: number;
  scheduled: number;
};

export type WeekdayCount = {
  label: string;
  sessions: number | null;
};

/** Percent complete, clamped and zero-safe. Plain counting, no weighting. */
export function toAdherence(completed: number, scheduled: number): Adherence {
  const percentage =
    scheduled <= 0 ? 0 : Math.min(100, Math.max(0, Math.round((completed / scheduled) * 100)));
  return { completed, percentage, scheduled };
}

/** Flattens a roadmap response into its session plans. */
export function flattenSessionPlans(roadmap: {
  weekPlans?: { dayPlans?: { sessionPlans?: SessionPlanRow[] }[] }[];
}): SessionPlanRow[] {
  const plans: SessionPlanRow[] = [];

  for (const week of roadmap.weekPlans ?? []) {
    for (const day of week.dayPlans ?? []) {
      for (const plan of day.sessionPlans ?? []) plans.push(plan);
    }
  }

  return plans;
}

export function plansOnDay(plans: readonly SessionPlanRow[], key: DayKey): SessionPlanRow[] {
  return plans.filter((plan) => dayKeyFromCalendarDate(plan.scheduledDate) === key);
}

export function plansInWindow(
  plans: readonly SessionPlanRow[],
  endKey: DayKey,
  length: number,
): SessionPlanRow[] {
  const window = new Set(dayKeyRange(endKey, length));
  return plans.filter((plan) => {
    const key = dayKeyFromCalendarDate(plan.scheduledDate);
    return key !== null && window.has(key);
  });
}

function isCompleted(plan: SessionPlanRow) {
  return plan.status === SESSION_PLAN_STATUS.COMPLETED;
}

/**
 * Adherence over a set of plans.
 *
 * Skipped and aborted sessions stay in the denominator — they were scheduled — while
 * only COMPLETED counts toward the numerator.
 */
export function planAdherence(plans: readonly SessionPlanRow[]): Adherence {
  return toAdherence(plans.filter(isCompleted).length, plans.length);
}

/** Completed sessions per weekday across a trailing window, oldest first. */
export function sessionsPerWeekday(
  plans: readonly SessionPlanRow[],
  endKey: DayKey,
  length: number,
): WeekdayCount[] {
  const scheduledByDay = new Map<DayKey, number>();
  const completedByDay = new Map<DayKey, number>();

  for (const plan of plans) {
    const key = dayKeyFromCalendarDate(plan.scheduledDate);
    if (!key) continue;
    scheduledByDay.set(key, (scheduledByDay.get(key) ?? 0) + 1);
    if (isCompleted(plan)) completedByDay.set(key, (completedByDay.get(key) ?? 0) + 1);
  }

  return dayKeyRange(endKey, length).map((key) => ({
    label: weekdayLabel(key) ?? key,
    // A day with nothing scheduled reads as absent, not as zero sessions done.
    sessions: scheduledByDay.has(key) ? (completedByDay.get(key) ?? 0) : null,
  }));
}

/**
 * Per-day completion percentage across a trailing window, oldest first.
 *
 * `null` on a day with nothing scheduled — there is no ratio to report, and drawing 0%
 * would read as a failed session rather than a rest day.
 */
export function dailyAdherenceSeries(
  plans: readonly SessionPlanRow[],
  endKey: DayKey,
  length: number,
): { key: DayKey; percentage: number | null }[] {
  const scheduledByDay = new Map<DayKey, number>();
  const completedByDay = new Map<DayKey, number>();

  for (const plan of plans) {
    const key = dayKeyFromCalendarDate(plan.scheduledDate);
    if (!key) continue;
    scheduledByDay.set(key, (scheduledByDay.get(key) ?? 0) + 1);
    if (isCompleted(plan)) completedByDay.set(key, (completedByDay.get(key) ?? 0) + 1);
  }

  return dayKeyRange(endKey, length).map((key) => {
    const scheduled = scheduledByDay.get(key);
    if (!scheduled) return { key, percentage: null };
    return {
      key,
      percentage: toAdherence(completedByDay.get(key) ?? 0, scheduled).percentage,
    };
  });
}

/** Distinct days in the window holding at least one completed session. */
export function countActiveDays(
  plans: readonly SessionPlanRow[],
  endKey: DayKey,
  length: number,
): number {
  const window = new Set(dayKeyRange(endKey, length));
  const days = new Set<DayKey>();

  for (const plan of plans) {
    if (!isCompleted(plan)) continue;
    const key = dayKeyFromCalendarDate(plan.scheduledDate);
    if (key && window.has(key)) days.add(key);
  }

  return days.size;
}

/** History rows inside a trailing window, by `WorkoutSessionSummary.date`. */
export function historyInWindow(
  rows: readonly SessionHistoryRow[],
  endKey: DayKey,
  length: number,
): SessionHistoryRow[] {
  const window = new Set(dayKeyRange(endKey, length));
  return rows.filter((row) => {
    const key = dayKeyFromTimestamp(row.date);
    return key !== null && window.has(key);
  });
}

export function sumVolume(rows: readonly SessionHistoryRow[]): number {
  return Math.round(rows.reduce((total, row) => total + row.totalVolume, 0));
}

export function sumSets(rows: readonly SessionHistoryRow[]): number {
  return rows.reduce((total, row) => total + row.totalSets, 0);
}
