/**
 * Workout reshaping for display.
 *
 * Reshape only: filter, group, sum, count, sort, format.
 *
 * Two wire constraints shape this file:
 *   1. `WorkoutSessionSummary` carries no `plan_id` / `session_plan_id` — that key exists
 *      only on events. Roadmap plans and execution history are therefore independent
 *      sources and are never joined row to row here.
 *   2. The roadmap uses `google.type.Date`, history uses `google.protobuf.Timestamp`, so
 *      both sides normalize to a day key first.
 */

import type { CalendarDateLike, DayKey, TimestampLike } from "./day-key";
import { dayKeyFromCalendarDate, dayKeyFromTimestamp, dayKeyRange, toDayKey } from "./day-key";

/** `SessionPlanStatus` as generated by protoc-gen-es. */
export const SESSION_PLAN_STATUS = {
  ABORTED: 4,
  COMPLETED: 2,
  PENDING: 1,
  SKIPPED: 3,
  UNSPECIFIED: 0,
} as const;

/** Structural subset of `PrescribedExercise`. */
export interface PrescribedExerciseRow {
  durationSeconds: number;
  restExerciseSec: number;
  restSetSec: number;
  targetSets: number;
}

/** Structural subset of `WorkoutPrescription`. */
export interface PrescriptionRow {
  coolDowns?: PrescribedExerciseRow[];
  mainExercises?: PrescribedExerciseRow[];
  warmUps?: PrescribedExerciseRow[];
}

/** Structural subset of `SessionPlan`. */
export interface SessionPlanRow {
  prescription?: PrescriptionRow;
  scheduledDate?: CalendarDateLike;
  sessionPlanId: string;
  slotTime?: string;
  status: number;
  targetMuscleGroups?: string[];
}

/** Structural subset of `WorkoutSessionSummary`. */
export interface SessionHistoryRow {
  averageFormScore?: number;
  date?: TimestampLike;
  sessionId: string;
  totalSets: number;
  totalVolume: number;
}

export interface Adherence {
  completed: number;
  percentage: number;
  scheduled: number;
}

/** Percent complete, clamped and zero-safe. Plain counting, no weighting. */
export function toAdherence(completed: number, scheduled: number): Adherence {
  const percentage =
    scheduled <= 0 ? 0 : Math.min(100, Math.max(0, Math.round((completed / scheduled) * 100)));
  return { completed, percentage, scheduled };
}

/** Flattens a roadmap response into its session plans. */
export function flattenSessionPlans(roadmap: {
  weekPlans?: { dayPlans?: { sessionPlans?: SessionPlanRow[] }[] }[];
}): SessionPlanRow[] {
  const plans: SessionPlanRow[] = [];

  for (const week of roadmap.weekPlans ?? []) {
    for (const day of week.dayPlans ?? []) {
      for (const plan of day.sessionPlans ?? []) {plans.push(plan);}
    }
  }

  return plans;
}

export function plansOnDay(plans: readonly SessionPlanRow[], key: DayKey): SessionPlanRow[] {
  return plans.filter((plan) => dayKeyFromCalendarDate(plan.scheduledDate) === key);
}

export function plansInWindow(
  plans: readonly SessionPlanRow[],
  endKey: DayKey,
  length: number,
): SessionPlanRow[] {
  const window = new Set(dayKeyRange(endKey, length));
  return plans.filter((plan) => {
    const key = dayKeyFromCalendarDate(plan.scheduledDate);
    return key !== null && window.has(key);
  });
}

function isCompleted(plan: SessionPlanRow) {
  return plan.status === SESSION_PLAN_STATUS.COMPLETED;
}

/**
 * Adherence over a set of plans.
 *
 * Skipped and aborted sessions stay in the denominator — they were scheduled — while
 * only COMPLETED counts toward the numerator.
 */
export function planAdherence(plans: readonly SessionPlanRow[]): Adherence {
  return toAdherence(plans.filter(isCompleted).length, plans.length);
}

/**
 * Prescribed minutes for one session: every exercise's work time plus its rests.
 *
 * Straight addition over `PrescribedExercise` fields — no coefficient, no estimate. This is
 * the session's prescribed length, which is the closest the wire gets to time spent:
 * `WorkoutSessionSummary` carries no `started_at`/`completed_at`, so actual elapsed time is
 * only knowable inside a live session and is not recoverable from history.
 */
export function prescribedMinutes(plan: SessionPlanRow): number {
  const groups = [
    plan.prescription?.warmUps ?? [],
    plan.prescription?.mainExercises ?? [],
    plan.prescription?.coolDowns ?? [],
  ];

  let seconds = 0;
  for (const group of groups) {
    for (const exercise of group) {
      const sets = Math.max(1, exercise.targetSets);
      seconds += sets * (exercise.durationSeconds + exercise.restSetSec) + exercise.restExerciseSec;
    }
  }

  return Math.round(seconds / 60);
}

/** Prescribed minutes across the completed sessions on a given day. */
export function minutesTrainedOnDay(plans: readonly SessionPlanRow[], key: DayKey): number {
  return plansOnDay(plans, key)
    .filter(isCompleted)
    .reduce((total, plan) => total + prescribedMinutes(plan), 0);
}

/** Distinct days in the window holding at least one completed session. */
export function countActiveDays(
  plans: readonly SessionPlanRow[],
  endKey: DayKey,
  length: number,
): number {
  const window = new Set(dayKeyRange(endKey, length));
  const days = new Set<DayKey>();

  for (const plan of plans) {
    if (!isCompleted(plan)) {continue;}
    const key = dayKeyFromCalendarDate(plan.scheduledDate);
    if (key && window.has(key)) {days.add(key);}
  }

  return days.size;
}

/** History rows inside a trailing window, by `WorkoutSessionSummary.date`. */
export function historyInWindow(
  rows: readonly SessionHistoryRow[],
  endKey: DayKey,
  length: number,
): SessionHistoryRow[] {
  const window = new Set(dayKeyRange(endKey, length));
  return rows.filter((row) => {
    const key = dayKeyFromTimestamp(row.date);
    return key !== null && window.has(key);
  });
}

export function sumVolume(rows: readonly SessionHistoryRow[]): number {
  return Math.round(rows.reduce((total, row) => total + row.totalVolume, 0));
}

export interface WeeklyVolume {
  /** Total kg lifted in the week. `null` when no session was logged. */
  volumeKg: number | null;
  /** Monday of the week, as a day key. */
  weekStart: DayKey;
}

/** Monday of the ISO week containing `key`. */
function weekStartKey(key: DayKey): DayKey | null {
  const date = new Date(`${key}T00:00:00Z`);
  if (Number.isNaN(date.getTime())) {return null;}

  // GetUTCDay: Sunday is 0, so shift it to the end of the week.
  const offset = (date.getUTCDay() + 6) % 7;
  date.setUTCDate(date.getUTCDate() - offset);
  return toDayKey(date);
}

/**
 * Volume per week across a trailing window of weeks, oldest first.
 *
 * `GetWorkoutHistory` paginates by limit/offset with no date filter, so callers over-fetch
 * and this buckets by `WorkoutSessionSummary.date`. A week with no logged session yields
 * `null`, so absence never reads as a measured zero.
 */
export function weeklyVolumeSeries(
  rows: readonly SessionHistoryRow[],
  endKey: DayKey,
  weeks: number,
): WeeklyVolume[] {
  const thisWeek = weekStartKey(endKey);
  if (!thisWeek || weeks <= 0) {return [];}

  const byWeek = new Map<DayKey, number>();
  for (const row of rows) {
    const day = dayKeyFromTimestamp(row.date);
    const start = day ? weekStartKey(day) : null;
    if (!start) {continue;}
    byWeek.set(start, (byWeek.get(start) ?? 0) + row.totalVolume);
  }

  const series: WeeklyVolume[] = [];
  for (let back = weeks - 1; back >= 0; back -= 1) {
    const start = new Date(`${thisWeek}T00:00:00Z`);
    start.setUTCDate(start.getUTCDate() - back * 7);
    const key = toDayKey(start);
    if (!key) {continue;}

    const total = byWeek.get(key);
    series.push({ volumeKg: total === undefined ? null : Math.round(total), weekStart: key });
  }

  return series;
}

export function sumSets(rows: readonly SessionHistoryRow[]): number {
  return rows.reduce((total, row) => total + row.totalSets, 0);
}
